#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-erubis
Version  : 2.7.0
Release  : 6
URL      : https://rubygems.org/downloads/erubis-2.7.0.gem
Source0  : https://rubygems.org/downloads/erubis-2.7.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-erubis-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
release::	2.7.0
copyright::	copyright(c) 2006-2011 kuwata-lab.com all rights reserved.

%package bin
Summary: bin components for the rubygem-erubis package.
Group: Binaries

%description bin
bin components for the rubygem-erubis package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n erubis-2.7.0
gem spec %{SOURCE0} -l --ruby > rubygem-erubis.gemspec

%build
gem build rubygem-erubis.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
erubis-2.7.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/erubis-2.7.0
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/erubis-2.7.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/CHANGES.txt
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/README.txt
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/benchmark/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/benchmark/bench.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/benchmark/bench_context.yaml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/benchmark/templates/_footer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/benchmark/templates/_header.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/benchmark/templates/bench_erb.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/benchmark/templates/bench_erubis.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/benchmark/templates/bench_eruby.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/bin/erubis
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/contrib/erubis
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/contrib/erubis-run.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/contrib/inline-require
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/ActionView.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/ActionView/TemplateHandlers/ErubisHandler.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/ERB.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/ArrayBufferEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/ArrayBufferEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/ArrayEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/ArrayEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Basic.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Basic/Converter.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Basic/Engine.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/BiPatternEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/BiPatternEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/CGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/CommandOptionError.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Context.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Converter.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/CppGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/DeleteIndentEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/DeleteIndentEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Ec.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Ecpp.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Ejava.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Ejavascript.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Engine.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Eperl.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Ephp.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/ErboutEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/ErboutEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/ErubisError.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Eruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapeEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapedEc.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapedEcpp.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapedEjava.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapedEjavascript.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapedEperl.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapedEphp.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapedEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/EscapedEscheme.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Escheme.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Evaluator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/FastEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Generator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/HeaderFooterEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/HeaderFooterEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Helpers.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Helpers/RailsFormHelper.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Helpers/RailsHelper.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Helpers/RailsHelper/TemplateConverter.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/InterpolationEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/InterpolationEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/JavaGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/JavascriptGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/Main.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/NoCodeEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/NoCodeEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/NoTextEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/NoTextEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/NotSupportedError.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/OptimizedEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/OptimizedGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/OptimizedXmlEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Converter.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Ec.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Ecpp.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Ejava.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Ejavascript.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Engine.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Eperl.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Ephp.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Eruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/Escheme.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PI/TinyEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PercentLineEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PercentLineEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PerlGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PhpGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PrefixedLineEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PrefixedLineEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PreprocessingEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PreprocessingHelper.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PrintEnabledEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PrintEnabledEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PrintOutEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PrintOutEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/PrintOutSimplifiedEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/RubyEvaluator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/RubyGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/SchemeGenerator.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/SimplifiedEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/SimplifyEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/StdoutEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/StdoutEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/StdoutSimplifiedEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/StringBufferEnhancer.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/StringBufferEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/StringIOEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/TinyEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/XmlEruby.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Erubis/XmlHelper.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/classes/Kernel.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/created.rid
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/README_txt.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/context_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/converter_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/ec_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/ecpp_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/ejava_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/ejavascript_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/enhanced_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/eperl_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/ephp_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/eruby_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/escheme_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine/optimized_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/engine_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/enhancer_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/error_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/evaluator_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/generator_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/helper_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/helpers/rails_form_helper_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/helpers/rails_helper_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/local-setting_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/main_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/preprocessing_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/tiny_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis/util_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/files/erubis_rb.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/fr_class_index.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/fr_file_index.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/fr_method_index.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/index.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc-api/rdoc-style.css
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc/docstyle.css
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/doc/users-guide.html
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/example.ec
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/example.ecpp
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/example.ejava
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/example.ejs
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/example.eperl
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/example.ephp
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/example.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/basic/example.escheme
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/pi/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/pi/example.ec
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/pi/example.ejava
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/pi/example.ejs
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/pi/example.eperl
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/pi/example.ephp
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/pi/example.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/examples/pi/example.escheme
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/context.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/ec.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/ecpp.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/ejava.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/ejavascript.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/enhanced.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/eperl.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/ephp.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/eruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/escheme.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine/optimized.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/helpers/rails_form_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/helpers/rails_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/local-setting.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/main.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/preprocessing.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/tiny.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/util.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/assert-text-equal.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/Example.ejava
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/array_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/arraybuffer_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/bipattern-example.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/bipattern_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/bufvar-example.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/bufvar-example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/context.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/context.yaml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/def_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/def_method.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/escape_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example.ec
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example.ecpp
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example.ejs
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example.eperl
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example.ephp
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example.escheme
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example1.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example1.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example1.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example10.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example10.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example10.xhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example10_x.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example11.php
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example11.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example11.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example11_C.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example11_N.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example11_U.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example11_php.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example1_x.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example2.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example2.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example2.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example2_trim.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example2_x.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example3.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example3.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example31.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example32.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example3_e.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example4.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example4.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example4.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example4_x.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example5.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example5.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example5.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example6.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example6.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example7.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example71.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example72.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example8.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example8_ruby.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example8_yaml.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example9.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example9.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example9.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example91.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example92.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example_c.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example_java.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example_js.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example_perl.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example_php.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example_scheme.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/example_scheme_display.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/fasteruby-example.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/fasteruby-example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/fasteruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/fasteruby.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/fasteruby.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/headerfooter-example.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/headerfooter-example2.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/headerfooter-example2.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/headerfooter_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/headerfooter_example2.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/interpolation_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/main_program1.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/main_program1.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/main_program2.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/main_program2.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/nocode-example.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/nocode-php.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/nocode_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/normal-eruby-test.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/normal_eruby_test.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/notext-example.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/notext-example.php
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/notext-php.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/notext_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/percentline-example.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/percentline_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/prefixedline-example.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/prefixedline-example.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/prefixedline_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/printenable_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/printenabled-example.eruby
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/printenabled-example.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/printstatement_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/simplify_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/stderr.log
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/stdout_exmple.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/stringbuffer_example.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/tail_260.result
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/tailnewline.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/template1.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/data/users-guide/template2.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/test-engines.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/test-enhancers.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/test-erubis.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/test-index-cgi.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/test-main.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/test-users-guide.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/erubis-2.7.0/test/testutil.rb
/usr/lib64/ruby/gems/2.3.0/specifications/erubis-2.7.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/erubis
